paths:
  data_root: "/data/market_data/binance/future"
  binance_assets: "/data/sigma/sigma/basic/binance_assets.json"

research:
  log_dir: "/home/zhangzhanyi/workspace/janus_vol_pred/janus_vol_pred/logs"
  output_root: "/data/sigma/zzy/janus/results/vol_pred_prod"
  features_output_dir: "features"
  results_output_dir: "results"
  fallback_book_ticker_output_dir: "raw_book_ticker"

production_train:
  trigger_utc_hour: 0
  trigger_utc_minute: 0
  fail_if_feature_dependency_missing: true
  log_dir: "/home/zhangzhanyi/workspace/janus_vol_pred/janus_vol_pred/logs"
  output_root: "/data/sigma/zzy/janus/results/vol_pred_prod"
  features_output_dir: "features"
  results_output_dir: "results_production"
  fallback_book_ticker_output_dir: "raw_book_ticker"

publish:
  enabled: true
  schedule_timezone: "Asia/Shanghai"
  schedule_hour: 8
  schedule_minute: 0
  remote_host: "54.64.180.220" # 远端 AWS 服务器地址
  remote_user: "root" # 登录远端机器所用的用户名
  ssh_key_path: "~/.ssh/jcd_aws_01/id_ed25519" # 用于 ssh/rsync 登录远端机器的私钥路径
  remote_results_root: "/root/workspace/janus_vol_pred/results" # 远端机器上模型存放的根目录
  rsync_bin: "rsync"
  ssh_bin: "ssh"
  files_to_sync:
    - "model.txt"
    - "quantile_transformer.pkl"
    - "feature_cols.json"
  publish_timeout_sec: 300 # 单次发布命令的超时时间，单位秒

realtime_predict:
  log_dir: "/root/workspace/janus_vol_pred/logs"
  output_root: "/root/workspace/janus_vol_pred"
  results_output_dir: "results"
  zmq_recv_addr: "tcp://127.0.0.1:5555"
  zmq_send_addr: "tcp://127.0.0.1:6666"
  model_lookback_days: 30
  warmup_minutes: 5

data_sources:
  enable_hangqing_fallback: true

hangqing:
  clickhouse_host: "13.231.173.109"
  clickhouse_port: 8123
  clickhouse_database: "marketData"
  clickhouse_username: "analyst"
  clickhouse_password: "analyst_E429G7Q5$q"

  exchange_name: "binance-futures"

logging:
  level: "INFO"

execution:
  instrument_type: "future"
  symbols:
    - XRPUSDT
  start_date: "2026-01-01"
  end_date: "2026-01-01"
  use_prev_day: true
  incremental_features_label: true
  incremental_features_max_retries: 2

sampling:
  interval_ns: 20_000_000
  warmup_minutes: 0

features:
  vol_windows:
    - 1
    - 3
    - 5
    - 10
    - 15
    - 30
    - 60
    - 120

label:
  vol_window: 5

train:
  train_downsample_freq: 20_000_000
  train_days: 7
  val_days: 1
  test_days: 1
  incremental: false
  max_retries: 2
  lgb_params:
    n_jobs: 30
    objective: "regression"
    num_leaves: 64
    max_depth: 8
    learning_rate: 0.05
    n_estimators: 1000
    min_data_in_leaf: 50
    feature_fraction: 0.8
    bagging_fraction: 0.8

multiprocess:
  max_workers: 4
