paths:
  data_root: "/data/market_data/binance/future"
  binance_assets: "/data/market_data/binance/basic/binance_assets.json"

research:
  log_dir: "/home/zhangzhanyi/workspace/janus_vol_pred/janus_vol_pred/logs"
  output_root: "/data/sigma/zzy/janus/results/vol_pred_prod"
  features_output_dir: "features"
  results_output_dir: "results"
  fallback_book_ticker_output_dir: "raw_book_ticker"

production_train:
  trigger_utc_hour: 0
  trigger_utc_minute: 0
  fail_if_feature_dependency_missing: true
  log_dir: "/home/zhangzhanyi/workspace/janus_vol_pred/janus_vol_pred/logs"
  output_root: "/data/sigma/zzy/janus/results/vol_pred_prod"
  features_output_dir: "features"
  results_output_dir: "results_production"
  fallback_book_ticker_output_dir: "raw_book_ticker"

publish:
  enabled: true
  schedule_timezone: "Asia/Shanghai"
  schedule_hour: 8
  schedule_minute: 0
  remote_host: "54.64.180.220" # 远端 AWS 服务器地址
  remote_user: "root" # 登录远端机器所用的用户名
  ssh_key_path: "~/.ssh/jcd_aws_01/id_ed25519" # 用于 ssh/rsync 登录远端机器的私钥路径
  remote_results_root: "/root/workspace/janus_vol_pred/results" # 远端机器上模型存放的根目录
  rsync_bin: "rsync"
  ssh_bin: "ssh"
  files_to_sync:
    - "model.txt"
    - "quantile_transformer.pkl"
    - "feature_cols.json"
  publish_timeout_sec: 300 # 单次发布命令的超时时间，单位秒

realtime_predict:
  log_dir: "/root/workspace/janus_vol_pred/logs"
  output_root: "/root/workspace/janus_vol_pred"
  results_output_dir: "results"
  zmq_recv_addr: "tcp://127.0.0.1:5555"
  zmq_send_addr: "tcp://127.0.0.1:6666"
  model_lookback_days: 30
  warmup_minutes: 5

data_sources:
  enable_hangqing_fallback: true

hangqing:
  clickhouse_host: "13.231.173.109"
  clickhouse_port: 8123
  clickhouse_database: "marketData"
  clickhouse_username: "analyst"
  clickhouse_password: "analyst_E429G7Q5$q"

  exchange_name: "binance-futures"

logging:
  level: "INFO"

execution:
  instrument_type: "future"
  symbols:
    # 204个币，回测适用于20250101-20260407，tick_size更新到2026-04-07

    # 流动性Top100
    - ETHUSDT # 格式还需调整，需弄成6小时一个文件
    - BTCUSDT # 格式还需调整，需弄成6小时一个文件
    # - SOLUSDT # lot_size变过
    - XRPUSDT
    - BNBUSDT
    - DOGEUSDT
    - ZECUSDT
    - SUIUSDT
    - VIRTUALUSDT
    - ENAUSDT
    # - 1000PEPEUSDT # 成交太大
    - LINKUSDT
    - AVAXUSDT
    - ADAUSDT
    - TAOUSDT
    - LTCUSDT
    - BCHUSDT
    - AIXBTUSDT
    - WLDUSDT
    - AAVEUSDT
    - WIFUSDT
    - PENGUUSDT
    - HBARUSDT
    - TRXUSDT
    - NEARUSDT
    - DIAUSDT
    - APTUSDT
    - DOTUSDT
    - FILUSDT
    - ZENUSDT
    - ARBUSDT
    - UNIUSDT
    # - KDAUSDT # tick_size变化
    - 1000BONKUSDT
    - CRVUSDT
    - EIGENUSDT
    - TIAUSDT
    - 1000SHIBUSDT
    - XLMUSDT
    - SNXUSDT
    - ETHFIUSDT
    - ONDOUSDT
    - ETCUSDT
    - OPUSDT
    - CAKEUSDT
    - DASHUSDT
    - PHBUSDT
    - FETUSDT
    - LDOUSDT
    - INJUSDT
    - AUCTIONUSDT
    - 1000FLOKIUSDT
    # - SEIUSDT # tick_size变化 2026-02-27 07:00 (UTC)
  # top50-100
    - TONUSDT
    - JUPUSDT
    # - MEUSDT # tick_size变化
    - APEUSDT
    - GALAUSDT
    - ATOMUSDT
    - PENDLEUSDT
    # - NEIROUSDT # tick_size变化 2026-02-27 07:00 (UTC)
    # - OMUSDT # 已退市
    - DYDXUSDT
    - BELUSDT
    - PNUTUSDT
    - ALGOUSDT
    # - CELOUSDT # tick_size变化 2026-04-02 06:30 (UTC) # tick_size变化 2026-03-19 06:30 (UTC)
    # - EDUUSDT  # tick_size变化 2026-04-02 06:30 (UTC)
    - RENDERUSDT
    - ICPUSDT
    - ORDIUSDT
    - TRBUSDT
    # - FLOWUSDT # tick_size变化 2026-01-28 09:00 (UTC)
    - JTOUSDT
    - WUSDT
  # top 70-100
    - SANDUSDT
    - VANAUSDT
    - ARUSDT
    - ENSUSDT
    - POLUSDT
    # - STRKUSDT # tick_size变化 2026-02-09 07:00 (UTC)
    - PYTHUSDT
    - ALICEUSDT
    - ARKMUSDT
    - IMXUSDT
    - MORPHOUSDT
    - TURBOUSDT
    - DOGSUSDT
    - ZROUSDT
    - CFXUSDT
    - YGGUSDT
    - API3USDT
    - SUSHIUSDT
    - VETUSDT
    - BBUSDT
    - MANAUSDT
    - JASMYUSDT
    - AVAUSDT
    - BOMEUSDT
    - 1000SATSUSDT
    - THETAUSDT
    # - RUNEUSDT # tick_size变化
    - PEOPLEUSDT
    - SKLUSDT
    - TWTUSDT
    # 流动性Top100之后
    - DEGOUSDT
    - 1000CHEEMSUSDT
    - IOUSDT
    - NMRUSDT
    - BATUSDT
    - ZKUSDT
    - NEOUSDT
    - GRTUSDT
    - KAVAUSDT
    # - LISTAUSDT # tick_size变化 2026-03-05 07:00 (UTC)
    - LPTUSDT
    - STXUSDT
    # - MEMEUSDT # tick_size变化 2026-02-12 07:00 (UTC)
    - BANANAUSDT
    - AXSUSDT
    - COMPUSDT
    - KMNOUSDT
    - RSRUSDT
    - 1000LUNCUSDT
    - XTZUSDT
    # - MAGICUSDT # tick_size变化 2026-02-12 07:00 (UTC)
    - BIGTIMEUSDT
    - LQTYUSDT
    - IOTAUSDT
    - GMTUSDT
    - QTUMUSDT
    - SUPERUSDT
    - ACTUSDT
    - 1MBABYDOGEUSDT
    # - SAGAUSDT  # tick_size变化
    - CHZUSDT
    - AIUSDT
    # - MINAUSDT # tick_size变化 2026-02-12 07:00 (UTC)
    - EGLDUSDT
    - QNTUSDT
    - ROSEUSDT
    - XAIUSDT
    - USDCUSDT
    - ZRXUSDT
    # - AXLUSDT # tick_size变化 2026-02-09 07:00 (UTC)
    - ACHUSDT
    - MASKUSDT
    - STORJUSDT
    - SSVUSDT
    - BEAMXUSDT
    - 1000XECUSDT
    - KSMUSDT
    - YFIUSDT
    - THEUSDT
    - ZILUSDT
    - SPELLUSDT
    - DEXEUSDT
    # - ALTUSDT # tick_size变化 2026-02-27 07:00 (UTC)
    - SUNUSDT
    - KNCUSDT
    - ARPAUSDT
    - 1INCHUSDT
    - BLURUSDT
    - C98USDT
    - FIDAUSDT
    # - TRUUSDT # tick_size变化 2026-02-12 07:00 (UTC)
    - CETUSUSDT
    - ONEUSDT
    - RLCUSDT
    # - LRCUSDT # 已退市
    - ILVUSDT
    - PHAUSDT
    - IDUSDT
    - AGLDUSDT
    - ONTUSDT
    # - VANRYUSDT # tick_size变化 2025-12-22 07:00 (UTC)
    - CHRUSDT
    - COTIUSDT
    - HOTUSDT
    - GMXUSDT
    - HFTUSDT
    # - FLMUSDT  # 已退市
    # - MANTAUSDT  # tick_size变化
    # - RDNTUSDT # tick_size变化 2026-02-12 07:00 (UTC)
    - CKBUSDT
    - CGPTUSDT
    - RVNUSDT
    - ORCAUSDT
    - ENJUSDT
    - COWUSDT
    - BANDUSDT
    - IOTXUSDT
    - WOOUSDT
    - USTCUSDT
    - ACEUSDT
    # - FXSUSDT # 已换名成FRAXUSDT，即原FXSUSDT的名称相当于已退市
    - SYSUSDT
    # - PIXELUSDT # tick_size变化 2026-02-09 07:00 (UTC)
    - GLMUSDT
    # - GTCUSDT # tick_size变化 2026-04-07 06:30 (UTC)
    - RAREUSDT
    - TLMUSDT
    # - SXPUSDT # 已退市
    - DENTUSDT
    - MAVUSDT
    - STGUSDT
    # - SCRUSDT # tick_size变化 2025-12-22 07:00 (UTC)
    # - TUSDT # tick_size变化 2026-02-12 07:00 (UTC)
    - CTSIUSDT
    # - ATAUSDT # tick_size变化 2026-04-07 06:30 (UTC)
    - DUSKUSDT
    - COSUSDT
    - SFPUSDT
    - SANTOSUSDT
    - ICXUSDT
    - CELRUSDT
    # - FIOUSDT  # tick_size变化 2026-03-18 07:00 (UTC)
    # - GHSTUSDT # 已退市
    # - SCRTUSDT  # tick_size变化 2026-03-05 07:00 (UTC)
    - RPLUSDT
    - JOEUSDT
    - ASTRUSDT
    - IOSTUSDT
    - OGNUSDT
    - MOVRUSDT
    - GASUSDT
    - POLYXUSDT
    - VELODROMEUSDT
    - HIGHUSDT
    - MTLUSDT
    # - NKNUSDT # 已退市
    # - DFUSDT # 已退市
    - ARKUSDT
    - HIVEUSDT
    - ONGUSDT
    - RONINUSDT
    # - REIUSDT # 已退市
    # - PERPUSDT  # 已退市
    - STEEMUSDT
    - XVSUSDT
    # - FLUXUSDT # tick_size变化 2026-02-27 07:00 (UTC)
    - LSKUSDT
    - OXTUSDT
    # - POWRUSDT # tick_size变化 2025-12-22 07:00 (UTC)
    # - WAXPUSDT # tick_size变化 2025-12-22 07:00 (UTC)
    - RIFUSDT
    # - QUICKUSDT # 已退市
  # start_date: "2026-03-01"
  start_date: "2026-03-18"
  end_date: "2026-04-12"
  use_prev_day: true
  incremental_features_label: true
  incremental_features_max_retries: 2

sampling:
  interval_ns: 20_000_000
  warmup_minutes: 0

features:
  vol_windows:
    - 1
    - 3
    - 5
    - 10
    - 15
    - 30
    - 60
    - 120

label:
  vol_window: 5

train:
  train_downsample_freq: 20_000_000
  train_days: 7
  val_days: 1
  test_days: 1
  incremental: true
  max_retries: 2
  lgb_params:
    n_jobs: 50
    objective: "regression"
    num_leaves: 64
    max_depth: 8
    learning_rate: 0.05
    n_estimators: 1000
    min_data_in_leaf: 50
    feature_fraction: 0.8
    bagging_fraction: 0.8

multiprocess:
  max_workers: 4
